AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example of lambda-service (and http API) written with Kotlin & Spring with the aws-serverless-java-container library
Resources:
  ExampleLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: net.ms.BarLambda::handleRequest
      Runtime: java8
      CodeUri: target/example-service-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 20
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /bar/{proxy+}
            Method: any
  FooLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: net.ms.FooLambda::handleRequest
      Runtime: java8
      CodeUri: target/example-service-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 20
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /foo/{proxy+}
            Method: any

Outputs:
  ExampleApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bar/info'
    Export:
      Name: ExampleService
  FooApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/foo/list'
    Export:
      Name: FooService
